// Conteúdo educativo estático do Portal — cuidados pós-procedimento
// Estrutura padronizada por procedimento

export const PROCEDIMENTOS_GUIAS = [
  {
    id: "toxina_botulinica",
    nome: "Toxina Botulínica",
    intro: "A toxina botulínica suaviza linhas de expressão e proporciona um aspecto natural e repousado.",
    antes: ["Evitar ácido acetilsalicílico (AAS) e anti-inflamatórios por 7 dias, se autorizado pelo médico.", "Não realizar procedimentos estéticos faciais invasivos nos 7 dias anteriores.", "Comunicar gravidez, amamentação ou infecções ativas."],
    primeiras_horas: ["Manter a cabeça ereta por 4 horas.", "Não deitar ou fazer esforço físico nas primeiras 4 horas.", "Não massagear a região aplicada."],
    primeiras_24h: ["Evitar atividade física intensa.", "Não fazer sauna, banho quente ou exposição solar direta.", "Evitar tocar ou coçar o rosto."],
    primeiros_7_dias: ["Evitar tratamentos faciais na região aplicada.", "Não realizar voos longos nas primeiras 24h, quando orientado.", "Reforçar hidratação e fotoproteção."],
    normal_sentir: ["Sensação de leve repuxamento.", "Pequeno edema (inchaço) nas áreas aplicadas, transitório.", "Sensibilidade local nas primeiras horas."],
    evitar: ["Massagem local.", "Atividade física intensa por 24h.", "Sauna e calor intenso por 7 dias.", "Deitar nas primeiras 4 horas."],
    quando_contato: ["Assimetria evidente após 7 dias.", "Dor intensa, calor ou vermelhidão persistente.", "Dificuldade para abrir os olhos ou visão alterada."],
    quando_retorno: "Retorno sugerido entre 14 e 21 dias para avaliação do resultado.",
  },
  {
    id: "preenchimento_facial",
    nome: "Preenchimento Facial",
    intro: "O preenchimento com ácido hialurônico devolve volume, contorno e harmonia ao rosto.",
    antes: ["Evitar AAS e anti-inflamatórios por 7 dias, se autorizado.", "Comunicar histórico de herpes labial para profilaxia, se necessário.", "Não fazer peelings ou lasers na região por 7 dias."],
    primeiras_horas: ["Aplicar compressas geladas leves, se orientado.", "Evitar deitar de bruços.", "Não massagear a área."],
    primeiras_24h: ["Evitar exercícios físicos.", "Evitar calor e sauna.", "Manter a cabeça elevada ao dormir."],
    primeiros_7_dias: ["Evitar exposição solar direta e usar protetor solar.", "Não realizar tratamentos faciais na área.", "Evitar dormir de bruços."],
    normal_sentir: ["Edema e leve roxidão no local da aplicação.", "Sensação de tensão na região.", "Pequeno desconforto à palpação."],
    evitar: ["Massagem na área sem orientação.", "Calor e sauna por 7 dias.", "Atividade física intensa por 48h."],
    quando_contato: ["Dor intensa, calor ou alteração de cor na área.", "Nódulos endurecidos persistentes.", "Lesões na pele na região aplicada."],
    quando_retorno: "Retorno sugerido entre 7 e 15 dias para avaliação e ajustes, se necessário.",
  },
  {
    id: "lips_signature",
    nome: "Lips Signature",
    intro: "O Lips Signature realça os lábios com naturalidade, equilíbrio e proporção ao seu rosto.",
    antes: ["Evitar AAS e anti-inflamatórios por 7 dias, se autorizado.", "Comunicar histórico de herpes labial para profilaxia.", "Hidrater os lábios nos dias anteriores."],
    primeiras_horas: ["Aplicar gelo leve por curtos períodos, se orientado.", "Não pressionar ou morder os lábios.", "Evitar falar muito nos primeiros minutos."],
    primeiras_24h: ["Evitar alimentos muito quentes ou picantes.", "Não usar batom ou produtos labiais por 24h.", "Evitar exercícios físicos."],
    primeiros_7_dias: ["Manter hidratação labial.", "Evitar sauna e calor.", "Usar protetor solar labial."],
    normal_sentir: ["Edema nos lábios por 24 a 72h.", "Sensação de tensão ou repuxamento.", "Leve desconforto."],
    evitar: ["Pressionar ou morder os lábios.", "Calor e sauna por 7 dias.", "Atividade física intensa por 48h."],
    quando_contato: ["Inchaço desproporcional ou assimétrico após 72h.", "Dor intensa ou lesões na região.", "Dificuldade para respirar ou engolir."],
    quando_retorno: "Retorno sugerido entre 10 e 15 dias para avaliação do resultado.",
  },
  {
    id: "rinomodelacao",
    nome: "Rinomodelação",
    intro: "A rinomodelação harmoniza o nariz com proporção refinada, sem alterar sua essência.",
    antes: ["Evitar AAS e anti-inflamatórios por 7 dias, se autorizado.", "Não usar óculos apertados nos dias anteriores.", "Comunicar histórico de sinusite."],
    primeiras_horas: ["Não tocar ou pressionar o nariz.", "Manter a cabeça ereta.", "Evitar espirrar com força."],
    primeiras_24h: ["Evitar deitar de lado ou bruços.", "Não usar óculos que pressionem o nariz.", "Evitar esforço."],
    primeiros_7_dias: ["Evitar óculos pesados apoiados no dorso nasal.", "Não realizar massagem facial.", "Evitar calor e sauna."],
    normal_sentir: ["Leve edema no dorso nasal.", "Sensação de tensão.", "Pequena sensibilidade local."],
    evitar: ["Pressionar ou massagear o nariz.", "Óculos apoiados na região por 7 dias.", "Atividade física intensa por 48h."],
    quando_contato: ["Alteração de cor no nariz.", "Dor intensa ou calor local.", "Dificuldade para respirar."],
    quando_retorno: "Retorno sugerido entre 7 e 15 dias para avaliação.",
  },
  {
    id: "bioestimuladores",
    nome: "Bioestimuladores de Colágeno",
    intro: "Os bioestimuladores ativam a produção natural de colágeno, melhorando a firmeza e a qualidade da pele.",
    antes: ["Evitar AAS e anti-inflamatórios por 7 dias, se autorizado.", "Não realizar outros estímulos de colágeno na mesma área por 30 dias.", "Hidratar a pele."],
    primeiras_horas: ["Massagem conforme orientação, se indicado.", "Não manipular a região além do orientado.", "Manter a região limpa."],
    primeiras_24h: ["Evitar calor e sauna.", "Não realizar atividade física intensa.", "Evitar exposição solar."],
    primeiros_7_dias: ["Manter hidratação e fotoproteção.", "Evitar tratamentos na área.", "Reforçar ingestão de água."],
    normal_sentir: ["Edema transitório.", "Pequenos nódulos na região, geralmente reabsorvidos.", "Sensação de tensão."],
    evitar: ["Anti-inflamatórios sem orientação.", "Calor e sauna por 7 dias.", "Atividade física intensa por 48h."],
    quando_contato: ["Nódulos doloridos persistentes.", "Calor ou vermelhidão intensa.", "Lesões na pele."],
    quando_retorno: "Retorno sugerido entre 30 e 60 dias para avaliação da evolução do colágeno.",
  },
  {
    id: "fios_sustentacao",
    nome: "Fios de Sustentação",
    intro: "Os fios promovem sustentação suave e estímulo de colágeno, com efeito gradual e natural.",
    antes: ["Evitar AAS e anti-inflamatórios por 7 dias, se autorizado.", "Comunicar histórico de queloides.", "Não fazer peelings na região por 15 dias."],
    primeiras_horas: ["Não manipular a região.", "Manter a cabeça ereta.", "Evitar expressões exageradas."],
    primeiras_24h: ["Dormir de costas, elevada.", "Não deitar de lado ou bruços.", "Evitar esforço e atividade física."],
    primeiros_7_dias: ["Evitar abrir muito a boca ou mímicas amplas.", "Não massagear o rosto.", "Evitar calor e sauna."],
    normal_sentir: ["Edema e leve traçado nas regiões dos fios.", "Sensação de repuxamento.", "Pequena dor à palpação."],
    evitar: ["Massagem facial.", "Dormir de bruços por 15 dias.", "Atividade física intensa por 7 dias."],
    quando_contato: ["Assimetria evidente após 7 dias.", "Protrusão ou rompimento visível de fio.", "Dor intensa ou calor local."],
    quando_retorno: "Retorno sugerido entre 15 e 30 dias para avaliação da sustentação.",
  },
  {
    id: "skin_quality",
    nome: "Skin Quality",
    intro: "A Skin Quality melhora textura, viço e luminosidade da pele com abordagem integrada e gradual.",
    antes: ["Hidratar a pele.", "Usar fotoproteção diária.", "Comunicar histórico de sensibilidade ou dermatites."],
    primeiras_horas: ["Não tocar o rosto com as mãos sujas.", "Não lavar com água quente.", "Não aplicar ácidos."],
    primeiras_24h: ["Usar apenas produtos indicados.", "Evitar maquiagem por 12h.", "Evitar calor."],
    primeiros_7_dias: ["Manter rotina de skincare indicada.", "Reforçar fotoproteção.", "Não introduzir novos produtos."],
    normal_sentir: ["Leve descamação.", "Sensibilidade transitória.", "Vermelhão discreto."],
    evitar: ["Ácidos não indicados.", "Esfoliação mecânica por 7 dias.", "Exposição solar sem proteção."],
    quando_contato: ["Vermelhidão intensa ou ardência persistente.", "Lesões na pele.", "Sensibilidade severa."],
    quando_retorno: "Retorno sugerido conforme plano individual, geralmente entre 15 e 30 dias.",
  },
  {
    id: "mento_mandibula",
    nome: "Mento e Contorno Mandibular",
    intro: "O tratamento do mento e do contorno mandibular traz equilíbrio, definição e harmonia ao perfil facial.",
    antes: ["Evitar AAS e anti-inflamatórios por 7 dias, se autorizado.", "Comunicar histórico de herpes na região.", "Não realizar peelings na área por 7 dias."],
    primeiras_horas: ["Não manipular a área.", "Aplicar gelo leve se orientado.", "Manter a cabeça ereta."],
    primeiras_24h: ["Evitar deitar de bruços.", "Evitar calor e atividade física.", "Não massagear."],
    primeiros_7_dias: ["Evitar dormir de bruços.", "Usar fotoproteção.", "Não realizar tratamentos na área."],
    normal_sentir: ["Edema e leve roxidão.", "Sensação de tensão no contorno.", "Pequena sensibilidade."],
    evitar: ["Massagem local.", "Calor e sauna por 7 dias.", "Atividade física intensa por 48h."],
    quando_contato: ["Assimetria evidente após 7 dias.", "Dor intensa ou calor local.", "Lesões na pele."],
    quando_retorno: "Retorno sugerido entre 7 e 15 dias para avaliação do contorno.",
  },
  {
    id: "full_face",
    nome: "Harmonização Facial Full Face",
    intro: "A Full Face integra técnicas para um resultado equilibrado, natural e coerente com sua essência.",
    antes: ["Seguir as orientações de cada técnica combinada.", "Evitar AAS e anti-inflamatórios por 7 dias, se autorizado.", "Planejar período de recuperação."],
    primeiras_horas: ["Manter a cabeça ereta.", "Não manipular o rosto.", "Aplicar gelo leve se orientado."],
    primeiras_24h: ["Evitar esforço, calor e sauna.", "Dormir de costas, elevada.", "Não massagear nenhuma região."],
    primeiros_7_dias: ["Evitar tratamentos faciais.", "Reforçar hidratação e fotoproteção.", "Evitar dormir de bruços."],
    normal_sentir: ["Edema mais generalizado nos primeiros dias.", "Sensação de tensão em múltiplas áreas.", "Roxidão em pontos de aplicação."],
    evitar: ["Massagem facial sem orientação.", "Atividade física intensa por 7 dias.", "Calor e sauna por 7 dias."],
    quando_contato: ["Edema assimétrico que não melhora após 72h.", "Dor intensa, calor ou alteração de cor.", "Qualquer sintoma que preocupe."],
    quando_retorno: "Retorno sugerido entre 14 e 21 dias para avaliação integrada do resultado.",
  },
];